### ISSUE TITLE
How is that Hatcher's Algebraic Topology is not mentioned?

### ISSUE THREAD

**Issue by Bolt64** [ystael/chicago-ug-math-bib#1]
I've noticed you've left out Allen Hatcher's _Algebraic Topology_ from your list of textbooks in that topic. I would send a pull request outlining the book, but I've only started reading it, and it might take me a while. I suggest if you've read it, might add an entry for it.

**Comment by ystael** [comment]
Remember that almost all of this was written in 1997-98, before the publication of many texts that are now standard. Hatcher is certainly one; the most glaring omission to my eyes is Stein & Shakarchi's _Princeton lectures on analysis_ series.
I am not qualified (now) to comment on algebraic topology texts; I would love for someone more current to add comparative reviews of, say, Hatcher, tom Dieck, and May's _Concise course_.
